# -*- coding: utf-8 -*-
"""
/***************************************************************************
 YoloQgis
                                 A QGIS plugin
 The plugin for training, detecting, and segmenting objects on raster maps using YOLO models.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-10-08
        copyright            : (C) 2025 by santerr80
        email                : santerr80@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load YoloQgis class from file YoloQgis.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .yolo_qgis import YoloQgis
    return YoloQgis(iface)
